### ISSUE TITLE
Ploomber scaffold raises PermissionError on Windows & WSL2

### ISSUE THREAD

**Issue by rdmolony** [ploomber/ploomber#323]
Hi there,

I suspect this is a Windows permissions issue which is specific to my laptop so I fear it may be impossible to reproduce!

Nonetheless I'm raising it here as an issue here regardless in case others have the same problem, with I hope a simple solution

I installed ploomber via conda on both OS's

---

On Windows:
```
➜ ploomber scaffold      
Enter project name:
* Alphanumeric
* Lowercase
* Underscores allowed
* First character cannot be numeric

Enter project name: x
Traceback (most recent call last):
  File "C:\Users\Rowan\mambaforge\envs\urban-atlas\Scripts\ploomber-script.py", line 9, in <module>
    sys.exit(cmd_router())
  File "C:\Users\Rowan\mambaforge\envs\urban-atlas\lib\site-packages\ploomber\cli\cli.py", line 120, in cmd_router
    cli()
  File "C:\Users\Rowan\mambaforge\envs\urban-atlas\lib\site-packages\click\core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\Rowan\mambaforge\envs\urban-atlas\lib\site-packages\click\core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "C:\Users\Rowan\mambaforge\envs\urban-atlas\lib\site-packages\click\core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))       
  File "C:\Users\Rowan\mambaforge\envs\urban-atlas\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\Rowan\mambaforge\envs\urban-atlas\lib\site-packages\click\core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\Rowan\mambaforge\envs\urban-atlas\lib\site-packages\ploomber\cli\cli.py", line 72, in scaffold
    scaffold_project.cli(project_path=None,
  File "C:\Users\Rowan\mambaforge\envs\urban-atlas\lib\site-packages\ploomber_scaffold\scaffold.py", line 176, in cli
  File "C:\Users\Rowan\mambaforge\envs\urban-atlas\lib\contextlib.py", line 117, in __enter__
    return next(self.gen)  File "C:\Users\Rowan\mambaforge\envs\urban-atlas\lib\importlib\resources.py", line 175, in _path_from_reader        
    opener_reader = reader.open_resource(norm_resource)
  File "<frozen importlib._bootstrap_external>", line 1055, in open_resource
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\Rowan\\mambaforge\\envs\\urban-atlas\\lib\\site-packages\\ploomber_scaffold\\template'
```
```
ploomber                      0.12.5
ploomber-scaffold             0.2.2
```

On WSL2:
```
❯ ploomber scaffold
Enter project name:
* Alphanumeric
* Lowercase
* Underscores allowed
* First character cannot be numeric

Enter project name: x
Traceback (most recent call last):
  File "/home/wsl-rowanm/mambaforge/envs/urban-atlas/bin/ploomber", line 10, in <module>
    sys.exit(cmd_router())
  File "/home/wsl-rowanm/mambaforge/envs/urban-atlas/lib/python3.9/site-packages/ploomber/cli/cli.py", line 120, in cmd_router
    cli()
  File "/home/wsl-rowanm/mambaforge/envs/urban-atlas/lib/python3.9/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/home/wsl-rowanm/mambaforge/envs/urban-atlas/lib/python3.9/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/home/wsl-rowanm/mambaforge/envs/urban-atlas/lib/python3.9/site-packages/click/core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/wsl-rowanm/mambaforge/envs/urban-atlas/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/wsl-rowanm/mambaforge/envs/urban-atlas/lib/python3.9/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/home/wsl-rowanm/mambaforge/envs/urban-atlas/lib/python3.9/site-packages/ploomber/cli/cli.py", line 72, in scaffold
    scaffold_project.cli(project_path=None,
  File "/home/wsl-rowanm/mambaforge/envs/urban-atlas/lib/python3.9/site-packages/ploomber_scaffold/scaffold.py", line 176, in cli
    copy_template(project_path, package=package, conda=conda)
  File "/home/wsl-rowanm/mambaforge/envs/urban-atlas/lib/python3.9/site-packages/ploomber_scaffold/scaffold.py", line 25, in copy_template
    with resources.path(ploomber_scaffold, 'template') as path_to_template:
  File "/home/wsl-rowanm/mambaforge/envs/urban-atlas/lib/python3.9/contextlib.py", line 117, in __enter__
    return next(self.gen)
  File "/home/wsl-rowanm/mambaforge/envs/urban-atlas/lib/python3.9/importlib/resources.py", line 175, in _path_from_reader
    opener_reader = reader.open_resource(norm_resource)
  File "<frozen importlib._bootstrap_external>", line 1055, in open_resource
IsADirectoryError: [Errno 21] Is a directory: '/home/wsl-rowanm/mambaforge/envs/urban-atlas/lib/python3.9/site-packages/ploomber_scaffold/template'
```
```
ploomber                      0.12.5
ploomber-scaffold             0.2.2
```

---

- [x] ploomber-scaffold raises IsADirectoryError on Linux on ``ploomber scaffold``
- [ ] ploomber-scaffold raises PermissionError on Windows on ``ploomber scaffold``

**Comment by rdmolony** [comment]
I tried running above in an elevated (admin) shell but no luck

**Comment by edublancas** [comment]
Not sure about the first error (`PermissionError`), but the second one (`IsADirectoryError`) is an issue due to a change in Python's `importlib.resources.path` (!) https://www.mail-archive.com/python-bugs-list@python.org/msg451088.html

Thanks for reporting this, this is an easy fix. Will post an updated version shortly!

**Comment by edublancas** [comment]
Please uninstall ploomber-scaffold and re-install from the dev branch:

```
pip uninstall ploomber-scaffold
pip install git+https://github.com/ploomber/scaffold@dev
```

That should fix the `IsADirectoryError` on `WSL2`, let me know what happens with the other error.

**Comment by edublancas** [comment]
Great. What happens on Windows, still getting the same `PermissionError`?

**Comment by rdmolony** [comment]
I couldn't find the ploomber-scaffold repo to make this PR there as the link is broken on pypi (didn't look too hard it seems!), made the fix there

**Comment by rdmolony** [comment]
Still have the same issue there unfortunately!  Do you want me to close this issue and move it to ploomber/scaffold instead or keep it here?

**Comment by edublancas** [comment]
Let's move the conversation to the other repo
